[book]
src = "src"
title = "Pulsate Specification"
language = "ja"
authors = ["Pulsate Project Team <info@pulsate.dev>"]

[build]
build-dir = "build"
create-missing = false

[preprocessor.alerts]

[preprocessor.pagetoc]
